//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingPlanTimeRefresh.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingPlanTimeRefresh.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 API 调用失败: {0} - {1} 的本地化字符串。
        /// </summary>
        internal static string ApiCallFailedFormat {
            get {
                return ResourceManager.GetString("ApiCallFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API Key 未配置 的本地化字符串。
        /// </summary>
        internal static string ApiKeyNotConfigured {
            get {
                return ResourceManager.GetString("ApiKeyNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API URL 未配置 的本地化字符串。
        /// </summary>
        internal static string ApiUrlNotConfigured {
            get {
                return ResourceManager.GetString("ApiUrlNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误，等待重试: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageFormat {
            get {
                return ResourceManager.GetString("ErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说一个冷笑话，不要重复常见段子，尽量新颖。 的本地化字符串。
        /// </summary>
        internal static string JokePrompt {
            get {
                return ResourceManager.GetString("JokePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string LanguageAuto {
            get {
                return ResourceManager.GetString("LanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string LanguageEn {
            get {
                return ResourceManager.GetString("LanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string LanguageZh {
            get {
                return ResourceManager.GetString("LanguageZh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用中... 的本地化字符串。
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动触发大模型 的本地化字符串。
        /// </summary>
        internal static string ManualTriggerButton {
            get {
                return ResourceManager.GetString("ManualTriggerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动触发,让模型讲个冷笑话 的本地化字符串。
        /// </summary>
        internal static string ManualTriggerPopupButton {
            get {
                return ResourceManager.GetString("ManualTriggerPopupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCP(月) 的本地化字符串。
        /// </summary>
        internal static string MCPMonthLabel {
            get {
                return ResourceManager.GetString("MCPMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次触发大模型: {0:HH:mm} ({1}分{2}秒后) 的本地化字符串。
        /// </summary>
        internal static string NextTriggerFormat {
            get {
                return ResourceManager.GetString("NextTriggerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        internal static string PinLabel {
            get {
                return ResourceManager.GetString("PinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 {0:MM/dd HH:mm} 的本地化字符串。
        /// </summary>
        internal static string ResetTextOther {
            get {
                return ResourceManager.GetString("ResetTextOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 {0:HH:mm} 的本地化字符串。
        /// </summary>
        internal static string ResetTextToday {
            get {
                return ResourceManager.GetString("ResetTextToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回结果 的本地化字符串。
        /// </summary>
        internal static string ResultHeader {
            get {
                return ResourceManager.GetString("ResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回结果(最后调用于 {0:HH:mm:ss}) 的本地化字符串。
        /// </summary>
        internal static string ResultTimestampFormat {
            get {
                return ResourceManager.GetString("ResultTimestampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token(5H) 的本地化字符串。
        /// </summary>
        internal static string Token5HLabel {
            get {
                return ResourceManager.GetString("Token5HLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token(周) 的本地化字符串。
        /// </summary>
        internal static string TokenWeekLabel {
            get {
                return ResourceManager.GetString("TokenWeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待触发... 的本地化字符串。
        /// </summary>
        internal static string WaitingPlaceholder {
            get {
                return ResourceManager.GetString("WaitingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}%已使用({1} Coding Plan) 的本地化字符串。
        /// </summary>
        internal static string WindowTitleFormat {
            get {
                return ResourceManager.GetString("WindowTitleFormat", resourceCulture);
            }
        }
    }
}
